"""add contact inquiry model

Revision ID: fa2ce06718c0
Revises: 6b55a1413191
Create Date: 2026-01-18 17:10:19.391307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2ce06718c0'
down_revision = '6b55a1413191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_inquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_inquiry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_inquiry_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_inquiry_timestamp'), ['timestamp'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['service_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_timestamp'))

    op.drop_table('message')
    with op.batch_alter_table('contact_inquiry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_inquiry_timestamp'))
        batch_op.drop_index(batch_op.f('ix_contact_inquiry_email'))

    op.drop_table('contact_inquiry')
    # ### end Alembic commands ###
